# KNN Algorithm in Supervised Machine Learning
# KNeighborClassifier of sklearn library

In [1]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

In [2]:
# Data Collection
X = np.array([
    [1,3500],
    [2,3200],
    [3,3000],
    [4,2500],
    [5,2300],
    [6,2000],
    [7,2200],
    [2,3700],
])
y= ['Unfit','Unfit','Unfit','Fit','Fit','Fit','Fit','Unfit']

In [3]:
# Create the model
model = KNeighborsClassifier(n_neighbors=3)

In [4]:
# Train the model
model.fit(X,y)

KNeighborsClassifier(n_neighbors=3)

In [5]:
# Predict
new_person = [[4.5,2600]]
predict = model.predict(new_person)
print('Predicted Result:', predict[0])

Predicted Result: Fit

In [8]:
# Predict from users
ex_hours=float(input('Enter your exercise hours'))
calory_intake=float(input('Enter your calory consume'))
predict_fit=model.predict([[ex_hours,calory_intake]])
print(f'Exercise Hour {ex_hours}, calory intake {calory_intake}, You are likely {predict_fit[0]}')

Enter your exercise hours 2.5
Enter your calory consume 4500

Exercise Hour 2.5, calory intake 4500.0, You are likely Unfit

# Second example

In [20]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

In [21]:
data=pd.read_csv('fruit_data.csv')
data

   Weight  Size   Fruit
0     150   7.0   Apple
1     160   7.2   Apple
2     200   8.0  Orange
3     210   8.2  Orange
4     180   7.5       ?

In [22]:
# Split the Data
X = data[['Weight','Size']]
y = data['Fruit']

In [23]:
# Model Creation
model = KNeighborsClassifier(n_neighbors=3)

In [24]:
# Train the model
model.fit(X,y)

KNeighborsClassifier(n_neighbors=3)

In [27]:
weight=float(input('Enter the fruit weight'))
size=float(input('Enter the fruit size'))
our_fruit= pd.DataFrame([[weight,size]], columns=['Weight','Size'])
predict_fruit=model.predict(our_fruit)
print(f'When weight is {weight}, size is {size}, the fruits is {predict_fruit[0]}')

Enter the fruit weight 200
Enter the fruit size 8

When weight is 200.0, size is 8.0, the fruits is Orange

# Third Example

In [28]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier

In [29]:
data=pd.read_csv('student_grade.csv')
data

   Hours_Studied  Assignments_Completed Grade
0            1.5                      1     C
1            2.0                      2     C
2            3.0                      3     B
3            4.0                      4     B
4            5.0                      5     A
5            6.0                      6     A

In [37]:
#Split the data
X = data[['Hours_Studied', 'Assignments_Completed']]
y = data['Grade']

In [38]:
# Create the model
model = KNeighborsClassifier(n_neighbors=3)

In [41]:
# Train the model
model.fit(X,y)

KNeighborsClassifier(n_neighbors=3)

In [42]:
new_hour=float(input('Enter the hour studied'))
new_assgn=float(input('Enter the amount of assignment that has been submitted'))
our_grade= pd.DataFrame([[new_hour,new_assgn]], columns=['Hours_Studied','Assignments_Completed'])
predict_grade=model.predict(our_grade)
print(f'When studied hours is {new_hour}, and number of submitted assignment is {new_assgn}, the grade is likely {predict_grade[0]}')

Enter the hour studied 3
Enter the amount of assignment that has been submitted 8

When studied hours is 3.0, and number of submitted assignment is 8.0, the grade is likely A